### ISSUE TITLE
Create Contributing.md file and add proper guidelines.

### ISSUE THREAD

**Issue by nirajpdn** [1teacher1/Hacktoberfest2022#7] opened 2022-10-18 02:56 UTC

**Comment by Pragya2056** [comment] 2022-10-18 03:43
I want to work on this. Please assign me.

**Comment by nirajpdn** [comment] 2022-10-18 04:03
@Pragya2056 , Awesome !!
Go ahead.

**Comment by Pragya2056** [comment] 2022-10-18 05:36
#15 
The issue is looked in the above PR

**Comment by Pragya2056** [comment] 2022-10-18 06:36
You can close the issue now.

**Closed** 2022-10-18 06:41 UTC
Labels: hacktoberfest
